apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod-volume
spec:
  containers:
    - name: frontend-container
      image: busybox
      command: ["sh", "-c", 'while true; do echo "Es wird in die Datei geschrieben"; date >> /data/data.txt; sleep 5; done']
      volumeMounts:
        - name: data-volume
          mountPath: /data


    - name: backend-container
      image: busybox
      command: ["sh", "-c", 'while true; do echo "Datei wird jetzt ausgelesen"; cat /data/data.txt; sleep 5; done']
      volumeMounts:
        - name: data-volume
          mountPath: /data


  volumes:
    - name: data-volume
      emptyDir: {}